
version: '3.8'
services:
  app:
    container_name: family-database
    image: family-database
    build: ./
    ports:
      - "8022:8022"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgresqldb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres